name: eventos
description: A premium mobile event operations platform.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: any
  go_router: any
  google_fonts: any
  intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any

flutter:
  uses-material-design: true
  assets:
    - assets/images/

