import 'package:flutter/material.dart';

class LucideIcons {
  static const IconData arrowLeft = Icons.arrow_back;
  static const IconData search = Icons.search;
  static const IconData users = Icons.group_outlined;
  static const IconData user = Icons.person_outline;
  static const IconData fileSignature = Icons.history_edu_outlined;
  static const IconData fileSpreadsheet = Icons.table_chart_outlined;
  static const IconData plus = Icons.add;
  static const IconData send = Icons.send;
  static const IconData alertCircle = Icons.warning_amber_rounded;
  static const IconData folder = Icons.folder_outlined;
  static const IconData phone = Icons.phone_outlined;
  static const IconData chevronRight = Icons.chevron_right;
  static const IconData edit2 = Icons.edit_outlined;
  static const IconData moreVertical = Icons.more_vert;
  static const IconData zap = Icons.bolt;
  static const IconData megaphone = Icons.campaign_outlined;
  static const IconData hash = Icons.tag;
  static const IconData clock = Icons.access_time;
  static const IconData checkCircle = Icons.check_circle_outline;
  static const IconData home = Icons.dashboard_outlined;
  static const IconData calendar = Icons.calendar_today_outlined;
  static const IconData bell = Icons.notifications_none_outlined;
  static const IconData alertTriangle = Icons.warning_amber_outlined;
  static const IconData x = Icons.close;
  static const IconData shieldCheck = Icons.verified_user_outlined;
  static const IconData plusCircle = Icons.add_circle_outline;
  static const IconData share2 = Icons.share_outlined;
  static const IconData mapPin = Icons.location_on_outlined;
  static const IconData fileText = Icons.description_outlined;
  static const IconData info = Icons.info_outline;
  static const IconData checkCheck = Icons.done_all;
  static const IconData check = Icons.check;
  static const IconData crown = Icons.workspace_premium_outlined;
  static const IconData award = Icons.emoji_events_outlined;
  static const IconData layers = Icons.layers_outlined;
  static const IconData fingerprint = Icons.fingerprint;
  static const IconData messageSquare = Icons.chat_bubble_outline;
  static const IconData phoneCall = Icons.phone_in_talk_outlined;
  static const IconData userX = Icons.person_off_outlined;
}
